//   companyFrom: "",
//   billTo: "",
//   shipTo: "",
//   item: "",
//   quantity: 0,
//   amount: 0,
//   currency: "",
//   terms: "",
//   total: 0,

export const inputs = [
  {
    id: 1,
    name: "companyFrom",
    type: "text",
    placeholder: "Company Name",
    errorMessage:
      "Company name should be 3-16 characters and shouldn't include any special character!",
    label: "Company Name from",
    pattern: "^[A-Za-z0-9]{3,16}$",
    required: true,
  },
  {
    id: 2,
    name: "billTo",
    type: "text",
    placeholder: "Bill to",
    label: "Bill to ",
    required: true,
    errorMessage: "The company you are billing can't be empty",
  },
  {
    id: 3,
    name: "shipTo",
    type: "text",
    placeholder: "Ship To",
    label: "Shipping to address ",
    required: true,
    errorMessage: "The company address is required",
  },
  {
    id: 4,
    name: "item",
    type: "text",
    placeholder: "Item",
    label: "Product Item ",
    required: true,
    errorMessage: "At least one item should be added",
  },
  {
    id: 5,
    name: "quantity",
    type: "text",
    placeholder: "Quantity",
    label: "Item Quantity",
    required: true,
    errorMessage: "At least one is required",
  },
  {
    id: 6,
    name: "amount",
    type: "text",
    placeholder: "Amount",
    label: "Amount",
    required: true,
    errorMessage: "At least one is required",
  },
  {
    id: 7,
    name: "currency",
    type: "text",
    placeholder: "Currency",
    label: "Currency",
    required: true,
    errorMessage: "Currency is required",
  },
  {
    id: 8,
    name: "terms",
    type: "textarea",
    placeholder: "Terms & Conditions",
    label: "Terms",
    required: false,
    errorMessage: "This",
  },
  {
    id: 9,
    name: "total",
    type: "text",
    placeholder: "Total",
    label: "Total",
    required: true,
    errorMessage: "Total is required and could be manually entered",
  },
];
